name: sleek_button
description: A simple but yet customizable button.
version: 0.1.1
homepage: https://github.com/aloisdeniel/sleek_button

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  freezed_annotation: ^0.7.1
  provider: ^4.0.4
  derived_colors: ^0.2.3
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner:
  freezed:  ^0.10.4
  flutter_test:
    sdk: flutter

flutter:
